apiVersion: v1
kind: Service
metadata:
  name: usermanagement-node-srv
spec:
  type: NodePort
  selector:
    app: usermanagementservice
  ports:
    - name: usermanagementservice
      protocol: TCP
      port: 80
      targetPort: 80